# Configurações de Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/portal_db
spring.datasource.username=postgres
spring.datasource.password=030606
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
# update: cria e atualiza as tabelas automaticamente baseado nas suas classes Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true